### ISSUE TITLE
Cut face cells

### ISSUE THREAD

**Issue by saberraz** [d2hydro/H2i_code_factory#5]
Currently, you output the stair-case cell faces:
![image](https://user-images.githubusercontent.com/2649047/154137910-c715c830-d42b-447a-926b-7e840d338045.png)

Would it be possible to have a similar layer with cut faces cells. It is not possible to create a mesh topology based on mesh edges. It is not topologically correct (see below the gap):
![image](https://user-images.githubusercontent.com/2649047/154138281-6d9603ac-ef0a-4339-b559-1a3f6abd82b5.png)

Furthermore, it is not possible for us to construct the mesh, without knowing which edge is from the quad tree cell and which one is cut through due to a ridge line.

**Comment by d2hydro** [comment]
resolved by new node_mesh
